name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  googleChatRoom:  # id of Chat Room
    description: 'Google Chat Room ID'
    required: true
  googleChatKey:  # Google Chat Webhook Key 
    description: 'Google Chat Webhook Key'
    required: true
  googleChatToken:  # Google Chat Webhook Token 
    description: 'Google Chat Webhook Token'
    required: true
  message:  # Message to be sent to Google Chat Room 
    description: 'Message to be sent'
    required: true
outputs:
  status: 
    description: 'Status Code of message publication'
  statusText: 
    description: 'Status Text of message publication'
runs:
  using: 'node12'
  main: 'index.js'